allprojects {
    version = '1.13'
    ext {
        appName = 'Hurdle Circle'
        gdxVersion = '1.14.2'
        gdxAiVersion = '1.8.2'
    }
    repositories {
        mavenCentral()
    }
}

subprojects {
    apply plugin: 'java'
    java {
        sourceCompatibility = JavaVersion.VERSION_1_8
        targetCompatibility = JavaVersion.VERSION_1_8
    }
    tasks.withType(JavaCompile).configureEach {
        options.encoding = 'UTF-8'
    }
}

project(':core') {
    apply plugin: 'java-library'
    dependencies {
        api "com.badlogicgames.gdx:gdx:$gdxVersion"
        api "com.badlogicgames.gdx:gdx-ai:$gdxAiVersion"
    }
}

project(':desktop') {
    dependencies {
        implementation project(':core')
        implementation "com.badlogicgames.gdx:gdx-backend-lwjgl3:$gdxVersion"
        implementation "com.badlogicgames.gdx:gdx-platform:$gdxVersion:natives-desktop"
    }
}
